apiVersion: batch/v1
kind: CronJob
metadata:
  name: ip-autoblock-job-production
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ip-autoblock-job-production
            image: osuakatsuki/firewall-rules:latest
            imagePullPolicy: Always
            command:
              - /scripts/bootstrap.sh
            env:
              - name: APP_ENV
                value: production
              - name: APP_COMPONENT
                value: ip-autoblock-job
              - name: KUBERNETES
                value: 'true'
              - name: PULL_SECRETS_FROM_VAULT
                value: '1'
              - name: VAULT_ADDR
                valueFrom:
                  secretKeyRef:
                    name: vault
                    key: address
              - name: VAULT_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: vault
                    key: token
              - name: APP_ENV
                value: production # TODO
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: osuakatsuki-registry-secret
        metadata:
          labels:
            sidecar.istio.io/inject: "false"
