import os

from dotenv import load_dotenv

load_dotenv()

DATADOG_API_KEY = os.environ["DATADOG_API_KEY"]
DATADOG_APPLICATION_KEY = os.environ["DATADOG_APPLICATION_KEY"]

CLOUDFLARE_ACCOUNT_ID = os.environ["CLOUDFLARE_ACCOUNT_ID"]
CLOUDFLARE_GLOBAL_API_KEY = os.environ["CLOUDFLARE_GLOBAL_API_KEY"]
CLOUDFLARE_DDOS_IPS_LIST_ID = os.environ["CLOUDFLARE_DDOS_IPS_LIST_ID"]
